### ISSUE TITLE
OG bug: PaulD's cdaudio.dat typo

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#1]
If the player is using the TR2 Steam version's cdaudio.dat file (not sure about GOG), there's an error that prevents a music track from playing properly in The Great Wall and Temple of Xian levels.

I found this response on TRF which outlines the problem: `The second code for track 33 in cdaudio.dat file is incorrect. It should be "01179345".`

This link gives an insight into how PaulD's audio solution works: https://www.tombraiderforums.com/showpost.php?p=3240199&postcount=1

[Saves.zip](https://github.com/LostArtefacts/TR2X/files/13215337/Saves.zip) for the two locations affected by this bug.

![1](https://github.com/LostArtefacts/TR2X/assets/94776985/4776d8ba-dff9-4cbc-a063-688d9dcad80d)
![2](https://github.com/LostArtefacts/TR2X/assets/94776985/84076d47-0838-4760-b590-556555e3c676)

**Comment by rr-** [comment]
@aredfan @Richard-L do you happen to know if it's OK for us to just ship fixed cdaudio.dat, or if there are multiple versions of it? Also do we know how TR2 custom levels handle music – do they just reuse the OG tracks, or do they repackage the files?

**Comment by Richard-L** [comment]
Hmm I must say I'm not knowledgeable enough. (Again) I'm mostly familiar with the PS1 version.

I do know that some fan levels like Sabatu's TR2 add in their own new audio (and voice) tracks.

**Comment by aredfan** [comment]
I reckon it's okay to do this because cdaudio.dat is distributed online with the [Tomb Raider Multi Patch](https://www.tombraiderchronicles.com/windows10/patch.html).  TRMP also got applied to the Steam/GOG versions ([according to Troye](https://www.tombraiderforums.com/showpost.php?p=8156545&postcount=3)).  I confirmed the TRMP and Steam versions to have this bug so presumably GOG won't be different.

TR2Main also ships it's own fixed cdaudio.dat but the code is slightly different, so probably not relevant to this issue.

**Comment by rr-** [comment]
@aredfan does the new music directory music backend that bypasses CDAudio altogether still exhibits this problem?

**Comment by aredfan** [comment]
@rr- The affected music now plays as expected.  This issue is resolved. 👍
