### ISSUE TITLE
TR2X bug: Lara is unable to slide down slopes without issues

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#107]
**Dev snapshot:** 0.2-130-ga17136e

**Comment by rr-** [comment]
@aredfan can you check if the issue is still present in the newest snapshot and if so, show a screenshot of an affected location?

**Comment by aredfan** [comment]
@rr- The issue Lara was having with slopes (in Lara's Home) is fixed in the latest snapshot. Thank you. 👍
