### ISSUE TITLE
TR2X bug: Game freezes in Lara's Home

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#109]
**Dev snapshot:** 0.2-137-g42d93bc

___________________

I took a screenshot each time the game froze. The steps for reproducing this bug is TBD but I think it has something to do with Winston.

First screenshot:
![Screenshot 1](https://github.com/user-attachments/assets/981d3f24-6dca-4ed4-af93-cd466a170a15)

Second screenshot. The game froze when Winston stepped onto the second click height.
![Screenshot 2](https://github.com/user-attachments/assets/51c25f6a-6454-4a31-a1d5-886ce63ddc86)

Third screenshot.
![Screenshot 3](https://github.com/user-attachments/assets/e7072286-815a-433e-9dfb-4e8cd724b966)

**Update:** Fourth screenshot.
![Screenshot 4](https://github.com/user-attachments/assets/ad69f21a-f955-44a0-85bc-6879352a5b44)

**Comment by rr-** [comment]
A simple way to reproduce it is to wait for the first demo in Venice to play; it freezes when Lara gets out of the water.
