### ISSUE TITLE
TR2X bug: Flickering skybox

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#117]
**Dev snapshot:** 0.2-145-g33f3dd1

____________________

The Great Wall, room 0.

![Screenshot](https://github.com/user-attachments/assets/5de936f8-f788-4b18-bf57-88673c7b2d41)

**Comment by rr-** [comment]
Fixed in the newest develop snapshot (22062b69e3ea11a5855cd4201f8196a5c9973d4e) via force push.
