### ISSUE TITLE
TR2X bug: The game freezes when End Level is triggered

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#118]
**Dev snapshot:** 0.2-145-g33f3dd1

______________________

The end level trigger in The Great Wall, room 65.

![Screenshot](https://github.com/user-attachments/assets/b010d757-b938-4eb6-a5a9-9c3135c5e728)

**Comment by rr-** [comment]
Fixed in the newest develop snapshot (22062b69e3ea11a5855cd4201f8196a5c9973d4e) via force push.
