### ISSUE TITLE
TR2X bug: Demo 1 - Different camera moment after killing the rat

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#119]
**Dev snapshot:** 0.2-153-ga72b5b2
______________________________

First part is OG, second part is TR2X.

Observe the part when the camera points up briefly after killing the rat (00:05). 

https://github.com/user-attachments/assets/c2723776-72a2-465f-9aab-1405e029126d

**Comment by aredfan** [comment]
I think the bug is Lara staying locked onto dead enemies and somehow missing many hits.  In OG, Lara doesn't miss dead enemies.

https://github.com/user-attachments/assets/0e76f5c2-9480-43b0-ba5e-fa0508c185fc

**Comment by rr-** [comment]
@aredfan the missed shots issue was fixed. I was unable to reproduce the demo issue – please LMK if it's working as expected.
