### ISSUE TITLE
TR2X: The game crashes when starting demo mode, new game and load game

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#120]
**Dev snapshot:** 0.2-155-g6f5e5da

________________

@rr- I saw your question about the demo and will check as soon as I'm able.

**Comment by rr-** [comment]
@aredfan I can't reproduce this problem on my end – can you please include a minidump file and/or a video demonstrating the issue? Thanks

EDIT: I found out a clue – this only happens with the release builds. The assets above won't be needed.
