### ISSUE TITLE
TR2X bug: The game crash when Lara picks up a discarded flare

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#121]
**Dev snapshot:** 0.2-157-g3aab9f8

__________________

**Steps to reproduce:**

1. Load Lara's Home
2. Teleport to room 86
3. Pick up the flares 
4. Take out a flare and discard it
5. Pick up the discarded flare

**Alternative steps to reproduce:**

1. Load Lara's Home
2. Teleport to room 86
3. Pick up the flares 
4. Press F5 and start a new game
5. Take out a flare and discard it
6. Pick up the discarded flare

**Comment by rr-** [comment]
The culprit seems to be `Lara_BaddieCollision`.
