### ISSUE TITLE
TR2X bug: Flickering light is widespread

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#122]
**Dev snapshot:** 0.2-161-g7382832

____________________

**Save:** [savegame.zip](https://github.com/user-attachments/files/16469703/savegame.zip)

The flickering light reaches the top of the shaft, the water below, and the room with the second water body. This is different from OG.

**TR2X:**

https://github.com/user-attachments/assets/336b3fbd-eea4-43b2-a832-380e36bf5c5c

**OG:**

https://github.com/user-attachments/assets/042e0d94-8da1-4219-bc64-7e344b7f37e3

**Comment by Richard-L** [comment]
One of the best effects in the game, such a vibe :)

Important to get it right.
