### ISSUE TITLE
TR2X bug: The game crashes when Lara kills the first enemy in Living Quarters

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#125]
**Dev snapshot:** 0.2-175-g4e8b52b

_________________

**Save:** [savegame.zip](https://github.com/user-attachments/files/16487351/savegame.zip)

First make Lara run forward to trigger the human enemy, then shoot to kill.

The bug is also present in 0.2.

**Comment by aredfan** [comment]
Regression since [0.1](https://github.com/LostArtefacts/TR2X/releases/tag/0.1).

**Comment by rr-** [comment]
@aredfan I can't reproduce this issue with either debug or a release build for the specified commit. Is there any specific way I need to kill the enemy with?

**Comment by aredfan** [comment]
@rr- I have Lara kill him with Automatic Pistols but it could be any weapon. I also found out earlier that the game can crash before triggering the enemy if I start changing Lara's weapons a few times with the number keys.

Should I upload the `TR2X.dmp`?

**Comment by rr-** [comment]
I think I got it – please LMK if it works now.

**Comment by aredfan** [comment]
@rr- The issues still persist on the latest dev build **0.2-188-g4010c11**.

Btw if I have Lara run pass the enemy, I get this:

![Screenshot1](https://github.com/user-attachments/assets/c1b212c5-2bbc-4b43-b56e-1800d242491c)

**Update:** I also noticed this save ([savegame.zip](https://github.com/user-attachments/files/16501723/savegame.zip)) stopped working. The same message appear as the one in the screenshot.

**Comment by rr-** [comment]
I'll need both TR2X.dmp and a TR2X.dll for closer investigation for the bug originally reported in this ticket.

**Comment by aredfan** [comment]
Here's the 2 files: [attachment removed]

**Comment by rr-** [comment]
@aredfan I apologize but I just realized that the optimized builds will not help me much since they're stripped of all symbols. Can I ask to re-test with this debug build?
https://home.wind.garden/serve/pub/TR2X-0.2-190-g0a714db-Windows.zip

**Comment by aredfan** [comment]
@rr- No worries, these things happen. 👍 

Re-tested and uploaded: [attachment removed]
