### ISSUE TITLE
TR2X bug: Texture bleeding

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#129]
**Dev snapshot:** 0.2-212-g395b9c7

___________________________

**A few screenshots:**

![Screenshot 1](https://github.com/user-attachments/assets/c2bdfdb7-5cd0-45f2-b832-58142db2920d)
![Screenshot 2](https://github.com/user-attachments/assets/340f592b-c9a5-4335-80e4-3b86c7826c45)
![Screenshot 3](https://github.com/user-attachments/assets/39c11790-375a-40d8-91a0-31576c89772a)

**Comment by rr-** [comment]
I'll need renderer settings for this, most notably I'm seeing the bilinear filter turned on but this might be also related to other things.

**Comment by aredfan** [comment]
I think you're right, the texture bleeding does disappear when bilinear filter is disabled (F8).

**My setup:**

![Screenshot](https://github.com/user-attachments/assets/6f05a7de-fb90-4f13-8421-dc3da8101e38)
