### ISSUE TITLE
TR2X Bug: underwater rendering broken in software render mode

### ISSUE THREAD

**Issue by walkawayy** [LostArtefacts/TR2X#132]
I can't take screenshots, but the works normally underwater in OG TR2. In TR2X, the pixels are rainbow colored and wrong. When the camera leaves the water, the game is rendered normally again.

**Comment by rr-** [comment]
![20240809_024716_hml](https://github.com/user-attachments/assets/c963f84e-ec0c-4726-a455-6c65b110c539)
Applies only to software rendering

**Comment by walkawayy** [comment]
![image](https://github.com/user-attachments/assets/5288264a-8ebc-4060-a712-39770dacb26b)
