### ISSUE TITLE
TR2X bug: Key visibility difference

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#134]
**Dev snapshot:** 0.2-226-g8c80c0b

Regression since [0.1.1](https://github.com/LostArtefacts/TR2X/releases/tag/0.1.1).

_________________

The Deck, room 61.

OG, there are 2 brief black blinks on the key sprite.

https://github.com/user-attachments/assets/dbb017ac-50d9-41ff-89cf-0ffe01101da3

TR2X, there's a long black blink on the key sprite.

https://github.com/user-attachments/assets/655dc8f5-00f5-4c47-a50e-62ea3225143e

This issue also affect the key visibility from above. (Room 102)

**OG:**
![OG](https://github.com/user-attachments/assets/8c1fd10a-33d9-46c1-9169-28dafe458ec1)

**TR2X:**
![TR2X](https://github.com/user-attachments/assets/8631f236-5579-486b-8a42-4a4efcba37e8)

______________________

**Save:** [savegame.zip](https://github.com/user-attachments/files/16581576/savegame.zip)

**Comment by aredfan** [comment]
Tibetan Foothills, room 18. This is probably the same bug. 

**OG:**
![OG](https://github.com/user-attachments/assets/fb49250e-818d-4207-b3f9-267899c2d66d)

**TR2X:**
![TR2X](https://github.com/user-attachments/assets/99216378-64d6-4854-892a-fa66b9d374dd)

**Save:** 
[savegame.zip](https://github.com/user-attachments/files/16582610/savegame.zip)

**Comment by Richard-L** [comment]
https://github.com/user-attachments/assets/74b92a75-29d4-434c-8f86-566bbc000616

Fwiw PS1 does the same thing. Is this some lighting effect, ie where shade is meant to be drawn, gone wrong?

**Comment by rr-** [comment]
@aredfan can you please check if this helps? https://home.wind.garden/serve/pub/TR2X-0.2-228-gaa8f55a-dirty-Windows.zip

**Comment by aredfan** [comment]
@rr- Yep this build fixed the issue. There's 2 brief black blinks on the key which matches OG behaviour. The secret stone dragon is fixed as-well, thank you.

**TR2X screenshots:**
![1](https://github.com/user-attachments/assets/f3dfd17e-0d0d-4c66-a1f2-2e5730244ce3)
![2](https://github.com/user-attachments/assets/293ee409-1279-4753-a717-60a4f0cc61da)
