### ISSUE TITLE
TR2X bug: Leopard get stuck between steps

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#138]
**Dev snapshot:** 0.2-230-g7430ea4

**Regression since:** [0.1](https://github.com/LostArtefacts/TR2X/releases/tag/0.1)

________________________

The first leopard to appear in Catacombs of the Talion gets stuck trying to climb a step between rooms 3 and 1.

![Image](https://github.com/user-attachments/assets/cad9b484-407b-40d0-9a0a-d25cd2991684)

**Save:**
[savegame.zip](https://github.com/user-attachments/files/16645650/savegame.zip)

**Edit:** Goons are affected too.  They can go down the stairs but they cannot get back up again.

**Comment by rr-** [comment]
It's a regression in `Creature_Animate`.
