### ISSUE TITLE
TR2X shortcut target path " -setup" doesn't do anything

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#14]
If the player want to access the external settings window, it can only be done after deleting the TR2 registry folder.

**Comment by rr-** [comment]
This is an OG bug right?

**Comment by aredfan** [comment]
I double checked and can confirm it's a TR2X bug.

I made a shortcut for the vanilla .exe and it does make the external settings window appear.  In TR2X's case, the shortcut just launches the game instead.

**Comment by rr-** [comment]
OK I see. Thanks.
