### ISSUE TITLE
TR2X bug: Demo 2 desync

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#154]
#153 

_________________

Lara doesn't fire the 5th shot needed to kill the diver. See the ammo count.

**TR2X:**

![TR2X](https://github.com/user-attachments/assets/8368d145-dca0-416b-8066-161223bdc7ce)

**OG**

![OG](https://github.com/user-attachments/assets/98bac188-68da-4a69-974a-faa416bef0eb)

**Comment by rr-** [comment]
Fixed in the PR
