### ISSUE TITLE
TR2X bug: Lara's head turn difference when harpoon is locked on enemy

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#155]
#153 

**Save:** [savegame.zip](https://github.com/user-attachments/files/16747515/savegame.zip)

__________________

I first noticed this during the demo when comparing versions. 

**TR2X:**

https://github.com/user-attachments/assets/0def540e-5d3e-4660-9d21-e6612d752bb6

**OG:**

https://github.com/user-attachments/assets/9ef02828-7b9a-4c07-befe-35e79eecb88c

**Comment by aredfan** [comment]
Here's a better video. It look like the issue affects all rifle weapons.

https://github.com/user-attachments/assets/c777247a-a5f7-4e3c-8640-54865711e4e3

**Save:** [savegame.zip](https://github.com/user-attachments/files/16747651/savegame.zip)

**Comment by rr-** [comment]
Fixed in the PR: https://github.com/LostArtefacts/TR2X/compare/e167f516e3137b6af11544264e18fcf6145f6c0b..04f8c9e7deeb6d2d181744f5f1ad258b7b474495
