### ISSUE TITLE
TR2X bug: HUD ammo sprites are missing when collecting all 3 secrets

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#158]
#157 

______________

See the individual grenade sprites.

**OG:**
![OG](https://github.com/user-attachments/assets/d94a9c20-c9d5-413b-a203-78de58af18dd)

**TR2X:**
![TR2X](https://github.com/user-attachments/assets/a6c5ea1f-fa97-4419-bdd2-461c3c64a8e8)

**Comment by rr-** [comment]
@aredfan can I ask for a savegame?

**Comment by aredfan** [comment]
@rr- Of course! Here's the save.

[SAVEGAME.zip](https://github.com/user-attachments/files/16765339/SAVEGAME.zip)

**Comment by rr-** [comment]
Fixed in the PR.
