### ISSUE TITLE
Feature request: Have Lara tilt when the fly cheat is activated 

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#166]
Currently Lara faces up vertically when the fly cheat is enabled.  Making Lara tilt in TR2X like she does in TR1X would make things consistent, and look aesthetically pleasing.

![Screenshot 1](https://github.com/user-attachments/assets/abd5782d-703c-4cb5-a2d2-acee8fc63978)

**Comment by rr-** [comment]
@lahm86 would you be so kind as to take a look at this one?

**Comment by lahm86** [comment]
> @lahm86 would you be so kind as to take a look at this one?

Yes, no problem. I agree the TR1X way is much nicer.

**Comment by aredfan** [comment]
It might be worth noting that Lara does a tilt if `/fly` is executed when floating on water, or in the boat.

In all other scenarios, Lara will always face up; when she's on the skidoo, the beginning of Offshore Rig, the ending of Home Sweet Home.

**Comment by Richard-L** [comment]
Love that this is added to TR2X so early. Very helpful for testing.

Other things that perhaps could be easy to miss for the underwater scenario are the air bar, bubbles and swim SFX going away.

**Comment by aredfan** [comment]
> Other things that perhaps could be easy to miss for the underwater scenario are the air bar, bubbles and swim SFX going away.

The swim SFX is still present, same as TR1X.

Lara does have bubbles when fly is activated, but it's quite subtle and only appear by her head.

![1](https://github.com/user-attachments/assets/3858e50f-2dd3-4f25-8228-efd2a17c7b89)

**Comment by Richard-L** [comment]
Oh yes you're right the swim SFX stays in TR1X, sorry.

I'd probably lose the bubbles though.
