### ISSUE TITLE
TR2X bug: passport is a blank state

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#173]
#171 

____________________

![Screenshot](https://github.com/user-attachments/assets/234e3bd4-915a-43be-a0b3-68553a4fff44)

**To reproduce:**

1. Have a savegame present.
2. In the main menu, open the passport to load game.
3. Flip pages to save game.
4. Then flip back.

**2nd method:**

1. Load a savegame.
2. Open the passport to load game or save game.

**Comment by rr-** [comment]
Fixed in the newest build at #171.
