### ISSUE TITLE
TR2X bug: the game crashes if loading the attached save file then /play 7

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#177]
#175 

**Save:** [savegame.zip](https://github.com/user-attachments/files/16861253/savegame.zip)

**Comment by aredfan** [comment]
Whoops, edited the title.

**Comment by rr-** [comment]
Thanks. Since I lack the context – can I ask how'd you make this savegame?

**Comment by aredfan** [comment]
@rr- I have a number of savegames from my previous run which was created a few weeks back. These saves are in the last 4 levels of the game, and when I load any of these saves then /play level 7, the game crashes.

Btw the latest build in #175 fixed this crash issue. 👍
