### ISSUE TITLE
TR2X bug: slight delay when using /tp during the starting cutscene of Offshore Rig

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#178]
#175

**Comment by aredfan** [comment]
Sorry, my bookkeeping was severely lacking today. This is a regression since [0.2](https://github.com/LostArtefacts/TR2X/releases/tag/0.2).

**Edit:** It'll be worth checking the ending in Home Sweet Home as well if this issue is worked on.

**Comment by rr-** [comment]
Fixed in #175
