### ISSUE TITLE
TR2X bug: Lara's posture doesn't correct when /tp from water to dry rooms

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#185]
**Dev snapshot:** 0.2-349-g51d1172

________________

https://github.com/user-attachments/assets/882065e4-744c-4a8b-84e6-72b8bb1a4bb2

**Comment by rr-** [comment]
Do we have the same issue in TR1?

**Comment by aredfan** [comment]
@rr- Nope, this issue isn't present in TR1X. Lara's posture is always correct when teleporting from water to dry rooms.

**Edit:** This might be relevant - Lara is skipping the 'fall in water' animation.

**0.2:**

https://github.com/user-attachments/assets/d8bae986-436d-4784-9129-11e4bb6ed447

**Dev snapshot:**

https://github.com/user-attachments/assets/945a1e52-8705-4809-8c99-e27f89509084
