### ISSUE TITLE
TR2X bug: when a new best time is set, the second best time isn't retained

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#195]
#193 

______________________

In OG, a new record is added whether you set a best time or just a time, see below.

![1](https://github.com/user-attachments/assets/53ef8205-b06f-414e-8d91-799db27d1c8f)

In TR2X, my 2nd attempt was a best time, but the 1st attempt record isn't retained.

![2](https://github.com/user-attachments/assets/cb1959ff-1375-448a-ab71-546b4e5a2653)

My 3rd attempt was also a best time, but once again the 2nd attempt record isn't retained.

![3](https://github.com/user-attachments/assets/678e63d6-c61c-4aa7-8280-d4cda0964a9d)

When I failed to set another best time in my fourth attempt, the record was retained along with my 3rd attempt.

![4](https://github.com/user-attachments/assets/d0c60813-e07c-43db-918b-b32ed11831e8)

**Comment by rr-** [comment]
@aredfan fixed in the PR.

**Comment by aredfan** [comment]
@rr- LGTM. 👍 

![1](https://github.com/user-attachments/assets/387ffe37-f536-46c4-bc3a-aa74893d8c29)
