### ISSUE TITLE
TR2X bug: Lara isn't automatically given key items in HSH

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#204]
**Dev snapshot:** 0.2-383-g7271da0

______________

**The missing items:**

- Dagger of Xian
- Gun Cupboard Key

![1](https://github.com/user-attachments/assets/f33e1a79-2e1f-4068-a970-86b8e5fd8b93)

![2](https://github.com/user-attachments/assets/9359bee9-be6c-444d-9c45-5a83d254e696)

**Comment by lahm86** [comment]
Does she get the Seraph in Tibet and Barkhang Monastery?

**Comment by aredfan** [comment]
> Does she get the Seraph in Tibet and Barkhang Monastery?

Yep, she still receives the Seraph automatically in those two levels.

**Edit:** It'll be worth checking if Lara can add the dagger to her inventory in The Dragon's Lair.
