### ISSUE TITLE
TR2X bug: the game crashes if cheats is used after reassigning a key

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#230]
**Dev snapshot:** 0.2-432-gfc79d77

________________

I found this regression when testing the recent PR but it was already present in the latest dev snapshot.

**Steps to reproduce:**

1. Open the main menu or inventory.
2. Select controls.
3. Change a key e.g. Flares to `F`.
4. Deselect controls.
5. Execute `/demo`, `/play` or `/load`.

**Comment by rr-** [comment]
Fixed in #229.
