### ISSUE TITLE
Move console commands code to libtrx

### ISSUE THREAD

**Issue by rr-** [LostArtefacts/TR2X#244]
- [x] Console_Cmd_Teleport
- [x] Console_Cmd_Fly
- [x] Console_Cmd_FlipMap
- [x] Console_Cmd_GiveItem
- [x] Console_Cmd_Kill
- [x] Console_Cmd_EndLevel
- [x] Console_Cmd_StartLevel
- [x] Console_Cmd_LoadGame
- [x] Console_Cmd_SaveGame
- [x] Console_Cmd_StartDemo
- [x] Console_Cmd_ExitToTitle
- [x] Console_Cmd_ExitGame
- [x] Console_Cmd_Abortion

**Comment by aredfan** [comment]
@rr- All the console commands listed in OP are now moved to libtrx. Is it ok to close this issue?

**Comment by rr-** [comment]
Yes
