### ISSUE TITLE
/ key doesn't work

### ISSUE THREAD

**Issue by Checkm8ra1n** [LostArtefacts/TR2X#249]
The / key doesn't open the console, tried with the numeric keypad and with ⇧+7 (for type / in ITALIAN keyboard)
P.S. Same issue with TR1X

**Comment by aredfan** [comment]
See the bottom right where console is highlighted. Try reassigning the console key to a different button.

![Screenshot](https://github.com/user-attachments/assets/a5e74e3b-5d18-4fad-9cac-50dba9d69cce)
