### ISSUE TITLE
Add Viva Las Vegas! to the GM collection

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#54]
I'd like to briefly mention the **Viva Las Vegas!** level - it's an earlier version of **Nightmare in Vegas** before it was overhauled for E3, it's a [long story](https://www.tombraiderforums.com/showpost.php?p=7302547&postcount=1).  I've been deliberating over whether to mention this as part of another issue before deciding it should be considered separately.

We could perhaps add Viva as a sixth GM level that the player can select from the bottom of the level list via the main menu. It would behave like a standalone level with its own set of stats, just like Nightmare.

Viva should be unlocked together with Nightmare, when all secrets from the first 4 levels are collected.  The reason for this is because some players may opt to skip Nightmare and go straight to Viva.

What do you guys think?  Would adding Viva to the GM collection in LostArtefacts/TRX#1621 be a good idea, or perhaps too unorthodox?

![3](https://github.com/LostArtefacts/TR2X/assets/94776985/3f2c2a1d-eac0-45a2-b62e-04816ba54ab3)

The file name for Viva is **level5**, we'll have to rename this file to something like **level5v2** or **level6** to avoid a clash with Nightmare.

**Update:** New Game's "Select Level" section is unlocked when all secrets in the first 4 levels are collected:
![4](https://github.com/LostArtefacts/TR2X/assets/94776985/042d3350-7cfa-4f3d-9ab1-082aa4bac96f)

**Comment by Richard-L** [comment]
Haha right, "cleavage-gate" :)

I would say it should be optional to the user which version is loaded, similar to how in TR1X's UB people can now choose whether to use the OG files or fan-modded music files.

**Comment by aredfan** [comment]
I've been rethinking this request and I feel that it should be shelved.  My thought is if users want to play Viva then it's a straightforward process of replacing the level file.
