### ISSUE TITLE
TR2X bug: Lara's shadow issue

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#64]
It looks like there's a z-buffer issue with Lara's shadow.

![Screenshot 1](https://github.com/LostArtefacts/TR2X/assets/94776985/92ae3367-9292-4a53-bcc5-d988f6a03ef0)

![Screenshot 2](https://github.com/LostArtefacts/TR2X/assets/94776985/a0ce2b46-ab39-49fb-bc67-3ead0a9438a3)

**Comment by rr-** [comment]
@aredfan can't replicate, please paste the version string.

**Comment by aredfan** [comment]
> @aredfan can't replicate, please paste the version string.

I'm unable to find the version string from the build earlier today. But I still got the files so can attach it here: [Snapshot.zip](https://github.com/LostArtefacts/TR2X/files/15108675/Snapshot.zip)

The shadow issue is also present in the latest snapshot build: TR2X.439e615

![Image](https://github.com/LostArtefacts/TR2X/assets/94776985/024ea02b-20c7-4059-b7f8-3fc9a089ac2c)

On tr1x, the version would appear in `Product version` but on tr2x there is no info here.
