### ISSUE TITLE
TR2X bug: Camera sometimes loses focus of Lara for one frame

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#65]
I noticed an issue with the camera losing focus of Lara for one frame.  It seems to happen randomly, I'm not sure how to reliably reproduce this bug.

**Development snapshot:** 08e5c30

________________

https://github.com/LostArtefacts/TR2X/assets/94776985/d403c3c1-e588-4c10-b09b-1acf4bd06b80

**Screenshot:**
![1 Screenshot](https://github.com/LostArtefacts/TR2X/assets/94776985/5f15d4a3-d27b-42a3-9133-84ccaa8d584c)

______________

https://github.com/LostArtefacts/TR2X/assets/94776985/8bb6b46b-5b4d-443d-a473-9b73693d8252

**Screenshot:**
![2 Screenshot](https://github.com/LostArtefacts/TR2X/assets/94776985/ebab8d02-414e-4a50-998e-eb64bd7b115a)

_______________

https://github.com/LostArtefacts/TR2X/assets/94776985/4af49877-4e5a-4e05-8101-352ef7748e07

**Screenshot:**
![3 Screenshot](https://github.com/LostArtefacts/TR2X/assets/94776985/12e9e968-c719-4147-b36e-63fa86f865a6)

___________________

https://github.com/LostArtefacts/TR2X/assets/94776985/1386a1fe-0733-412a-af48-79537ee496ae

**Screenshot:**
![4 Screenshot](https://github.com/LostArtefacts/TR2X/assets/94776985/8fba6483-5bf1-443f-b2e1-f5062dd8b4f7)

___________________

**New video:**

https://github.com/LostArtefacts/TR2X/assets/94776985/ee4c3a8d-d393-4549-b271-ae2ff668d533

**Screenshot:**
![5 Screenshot](https://github.com/LostArtefacts/TR2X/assets/94776985/8dfcc4fb-8f0c-4f75-8724-f5ca1f346467)

**Comment by rr-** [comment]
@aredfan any chance for finding a setup to reproduce this consistently, optionally paired with a savegame?

**Comment by rr-** [comment]
@aredfan actually I think I managed to fix it regardless. Could you please confirm once the new dev snapshot is in?

**Comment by aredfan** [comment]
@rr- I've tested Lara's Home and haven't seen any displaced camera moments since the latest snapshot. Thank you for fixing this issue.  👍
