### ISSUE TITLE
TR2X bug: Lara's hair issue when swimming

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#66]
In OG, when Lara is underwater, her braid will gradually rise upwards.  In tr2x, the braid becomes distorted instead.  The same issue affects Lara's braid when she's floating on the water surface.

To reproduce, have Lara swim underwater then keep her still and watch the braid.

**OG:**
![1](https://github.com/LostArtefacts/TR2X/assets/94776985/c40216a3-8eda-427a-b54d-1cec14ce7f87)

**tr2x:** 
![2](https://github.com/LostArtefacts/TR2X/assets/94776985/efb1345e-477d-4b36-a7a1-2cd240e73b78)

**Comment by rr-** [comment]
@aredfan I'm not 100% sure but I have a hunch that this might've been fixed with #65  in the latest dev snapshot.

**Comment by aredfan** [comment]
@rr- Confirmed, the braid is fixed in the latest snapshot.  Two birds and one stone. 😄
