### ISSUE TITLE
Demo mode

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TR2X#7]
Currently no demos seems to be available, or they are turned off. It would be lovely to have the option toggle from TR1X to en/-disable them.

**Comment by rr-** [comment]
Hi, the demos are working for me and @aredfan so I think this may be closed?

The timeout in TR2 is high – it's 30 seconds, unlike in TR1X which has 16 seconds.

**Comment by Richard-L** [comment]
I'm happy to check again soon.

Just so I can check: In which folder does TR2X expect which demo files?

**Comment by aredfan** [comment]
Having `BOAT.TR2` `KEEL.TR2` and `SKIDOO.TR2` in the DATA folder should be enough.

**Edit:** It's worth mentioning you can execute `/demo` to see the demo modes even quicker.

**Comment by rr-** [comment]
@Richard-L ping

**Comment by Richard-L** [comment]
Yep, works fine. Will close.
