### ISSUE TITLE
TR2X bug: Texture issue on medi packs

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#70]
**Dev snapshot:** 0.1-7-gd58a3f3

Note the small yellow boxes.

**OG:**
![1](https://github.com/LostArtefacts/TR2X/assets/94776985/3b75ca34-f5d8-46f0-92c9-13cbeb7ed262)

**TR2X:**
![2](https://github.com/LostArtefacts/TR2X/assets/94776985/2b216d0b-9a5b-4027-8373-f271305c239d)

**Comment by Richard-L** [comment]
Would this be a hardware/software renderer concern?

Also reminds me of https://github.com/LostArtefacts/TRX/issues/1646

**Comment by aredfan** [comment]
@rr- My setup:

![1](https://github.com/LostArtefacts/TR2X/assets/94776985/8d593a42-9ee7-4a4f-bfbb-b6c6d3dd374a)
