### ISSUE TITLE
TR2X bug: Stopwatch ticking hand issue

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#71]
**Dev snapshot:** 0.1-7-gd58a3f3

Start New Game then take out the stopwatch.  You'll see the button on the stopwatch is rotating and the red hand doesn't move. 

![Screenshot](https://github.com/LostArtefacts/TR2X/assets/94776985/6bd3769b-56ae-4357-bf9b-4c19ae8a8011)

**Comment by rr-** [comment]
Thanks. Fixed in the latest develop.
