### ISSUE TITLE
TR2X bug: Flashing indicator when the dev console is open before typing, is absent

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#90]
**Dev snapshot:** 0.1.1-24-g01d3c59

____________________

In my case, it's a flashing `#` on the main menu, and a `&` in-game.  It doesn't appear until after you start typing.

**Comment by rr-** [comment]
The reason for using `#` / `&` (which are both less than attractive), is because there is no suitable sprite available for depicting the flashing caret character. Improving it will likely need to wait for the injection framework some time down the line. As for the caret missing I'll work on that.

**Comment by rr-** [comment]
@aredfan does this issue still occur for you with the latest dev snapshot?

**Comment by aredfan** [comment]
@rr- I've checked and the flashing carat is working again when the dev console is opened, thank you. 👍 

I found a second issue while testing that may not be new.  If I press `/` twice in a row or press `/` after typing something, it causes the characters to remain on-screen.

**Comment by rr-** [comment]
@aredfan Thanks. This should be fixed in the latest dev snapshot that's going to be out in a few minutes.

**Comment by aredfan** [comment]
@rr- I've tested on latest and the second issue is resolved.  LGTM. 👍
