### ISSUE TITLE
OG bug: Dropped flares end up below the surface

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#93]
A bug that exist from TR2 to TRC, at least on PC.

When Lara takes out a flare and drop it, the flare seem to end up below the surface. 

https://github.com/LostArtefacts/TR2X/assets/94776985/b93072b4-d61f-4fc2-9c11-b79f0a76b8fe

**Comment by Richard-L** [comment]
Can somewhat reproduce this on PS1, but not fully (?)

https://github.com/LostArtefacts/TR2X/assets/4934209/2eb8b47b-8521-46a8-bf78-d679d90b7fc2

Could this just be an issue of Z fighting? Believe we may have had a related issue for that?

Interestingly I notice the dropped flare just seems to be a flat texture on the ground. Perhaps a separate issue may be to make it a 3D object?

**Comment by aredfan** [comment]
@Richard-L Thank you for checking the PS1 version.

You're right, it does look like Z fighting.  I just went into settings and disabled the Z Buffer option.  This is what dropped flares look like with the option disabled.

![1](https://github.com/LostArtefacts/TR2X/assets/94776985/23607488-c0ad-4a70-9a9d-265cf90e0365)

**Comment by Richard-L** [comment]
Nice 👍

Curiously it seems to be a 3d object in the PC version.

I suppose when z-fighting is touched it'll be worthwhile rechecking this issue and then likely close it. What do you think?

**Comment by aredfan** [comment]
Sounds like a good plan. 👌

**Comment by aredfan** [comment]
Merging with LostArtefacts/TRX#1595
