### ISSUE TITLE
OG bug: Water effect visible at the base of the boat

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TR2X#96]
Astutely observed by @Richard-L

F7 can be used to toggle the Z Buffer option in-game.

https://github.com/LostArtefacts/TR2X/assets/94776985/752436c1-23fa-4eff-9a69-66e6d5811299

**Comment by Richard-L** [comment]
Thank you 🙏 

@lahm86 I'm wondering, regardless of the z-fighting, the ground texture of the boat looks unfortunately similar to the PC water colour itself. Would this at all be a similar case of these texture fixes you'd done for TR1X? https://youtu.be/b0dSnCWEGbk?si=r3MIVvm0yMuqiBhF&t=70

**Comment by aredfan** [comment]
Merging with LostArtefacts/TRX#1595
